name: Auto merge

on:
  workflow_dispatch:
  workflow_call:

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Merge pull requests (automerge-action)
        uses: pascalgn/automerge-action@v0.16.2
        with:
          super_secret: ${{ secrets.TOKEN }}
        env:
          GITHUB_TOKEN: "${{ secrets.TOKEN }}"
          MERGE_LABELS: "automerge"
          MERGE_METHOD: "squash"
          BASE_BRANCHES: "main"
